# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant.configure("2") do |config|
  config.vm.box = "paanini/ubuntu1804-openjdk-11"

  config.vm.hostname = "vagrant-manolete"
  config.vm.network "forwarded_port", guest: 80, host: 8585
  config.vm.network "private_network", ip: "192.168.100.100"
  config.vm.synced_folder "data", "/home/vagrant/data"
 
  config.vm.provider "virtualbox" do |vb| 
    vb.gui = false 
    vb.memory = "2048" 
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    
    sudo apt install vim -y
    sudo apt install openjdk-11-jdk -y

  SHELL
end
